name: MasterDeployCI
on:
  push:
    branches:
      - master
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Switch to EbikeFirmwareLoader Folder
      run: |
        cd EbikeFirmwareLoader
        ls -la
    - name: Bump version and push tag
      uses: anothrNick/github-tag-action@master
      env:
        GITHUB_TOKEN: ${{ secrets.EBIKE_RELEASE_TOKEN }}
        REPO_OWNER: keithweaver